"""
The Sims 4 Community Library is licensed under the Creative Commons Attribution 4.0 International public license (CC BY 4.0).
https://creativecommons.org/licenses/by/4.0/
https://creativecommons.org/licenses/by/4.0/legalcode

Copyright (c) COLONOLNUTTY
"""
from typing import Tuple, Any
from sims4communitylib.modinfo import ModInfo
from sims4communitylib.services.commands.common_console_command import CommonConsoleCommand
from sims4communitylib.services.commands.common_console_command_output import CommonConsoleCommandOutput
from sims4communitylib.utils.resources.common_skill_utils import CommonSkillUtils


class _S4CLReaderForUpdate:
    # noinspection SpellCheckingInspection
    CONVERSIONS = {
        'SKILL_FITNESS': 'FITNESS',
        'STATISTIC_SKILL_ADULTMAJOR_ACTING': 'ACTING',
        'STATISTIC_SKILL_ADULTMAJOR_APOTHECARY': 'APOTHECARY',
        'STATISTIC_SKILL_ADULTMAJOR_ARCHAEOLOGY': 'ARCHAEOLOGY',
        'STATISTIC_SKILL_ADULTMAJOR_BAKING': 'BAKING',
        'STATISTIC_SKILL_ADULTMAJOR_BARTENDING': 'MIXOLOGY',
        'STATISTIC_SKILL_ADULTMAJOR_CHARISMA': 'CHARISMA',
        'STATISTIC_SKILL_ADULTMAJOR_COMEDY': 'COMEDY',
        'STATISTIC_SKILL_ADULTMAJOR_DJMIXING': 'DJ_MIXING',
        'STATISTIC_SKILL_ADULTMAJOR_EQUESTRIANSKILL': 'EQUESTRIAN_SKILL',
        'STATISTIC_SKILL_ADULTMAJOR_FABRICATION': 'FABRICATION',
        'STATISTIC_SKILL_ADULTMAJOR_FISHING': 'FISHING',
        'STATISTIC_SKILL_ADULTMAJOR_FLOWERARRANGING': 'FLOWER_ARRANGING',
        'STATISTIC_SKILL_ADULTMAJOR_GARDENING': 'GARDENING',
        'STATISTIC_SKILL_ADULTMAJOR_GEMOLOGY': 'GEMOLOGY',
        'STATISTIC_SKILL_ADULTMAJOR_GOURMETCOOKING': 'GOURMET_COOKING',
        'STATISTIC_SKILL_ADULTMAJOR_GUITAR': 'GUITAR',
        'STATISTIC_SKILL_ADULTMAJOR_HANDINESS': 'HANDINESS',
        'STATISTIC_SKILL_ADULTMAJOR_HERBALISM': 'HERBALISM',
        'STATISTIC_SKILL_ADULTMAJOR_HOMESTYLECOOKING': 'COOKING',
        'STATISTIC_SKILL_ADULTMAJOR_KNITTING': 'KNITTING',
        'STATISTIC_SKILL_ADULTMAJOR_LOGIC': 'LOGIC',
        'STATISTIC_SKILL_ADULTMAJOR_MISCHIEF': 'MISCHIEF',
        'STATISTIC_SKILL_ADULTMAJOR_PAINTING': 'PAINTING',
        'STATISTIC_SKILL_ADULTMAJOR_PARENTING': 'PARENTING',
        'STATISTIC_SKILL_ADULTMAJOR_PHOTOGRAPHY': 'PHOTOGRAPHY',
        'STATISTIC_SKILL_ADULTMAJOR_PIANO': 'PIANO',
        'STATISTIC_SKILL_ADULTMAJOR_PIPEORGAN': 'PIPE_ORGAN',
        'STATISTIC_SKILL_ADULTMAJOR_POTTERY': 'POTTERY',
        'STATISTIC_SKILL_ADULTMAJOR_PROGRAMMING': 'PROGRAMMING',
        'STATISTIC_SKILL_ADULTMAJOR_RESEARCHDEBATE': 'RESEARCH_AND_DEBATE',
        'STATISTIC_SKILL_ADULTMAJOR_ROBOTICS': 'ROBOTICS',
        'STATISTIC_SKILL_ADULTMAJOR_ROCKCLIMBING': 'ROCK_CLIMBING',
        'STATISTIC_SKILL_ADULTMAJOR_ROCKETSCIENCE': 'ROCKET_SCIENCE',
        'STATISTIC_SKILL_ADULTMAJOR_ROMANCE': 'ROMANCE',
        'STATISTIC_SKILL_ADULTMAJOR_SINGING': 'SINGING',
        'STATISTIC_SKILL_ADULTMAJOR_SKIING': 'SKIING',
        'STATISTIC_SKILL_ADULTMAJOR_SNOWBOARDING': 'SNOWBOARDING',
        'STATISTIC_SKILL_ADULTMAJOR_TATTOOING': 'TATTOOING',
        'STATISTIC_SKILL_ADULTMAJOR_VETERINARIAN': 'VETERINARIAN',
        'STATISTIC_SKILL_ADULTMAJOR_VIDEOGAMING': 'VIDEO_GAMING',
        'STATISTIC_SKILL_ADULTMAJOR_VIOLIN': 'VIOLIN',
        'STATISTIC_SKILL_ADULTMAJOR_WELLNESS': 'WELLNESS',
        'STATISTIC_SKILL_ADULTMAJOR_WRITING': 'WRITING',
        'STATISTIC_SKILL_ADULTMINOR_DANCING': 'DANCING',
        'STATISTIC_SKILL_ADULTMINOR_ENTREPRENEUR': 'ENTREPRENEUR',
        'STATISTIC_SKILL_ADULTMINOR_JUICEFIZZING': 'JUICE_FIZZING',
        'STATISTIC_SKILL_ADULTMINOR_JUICEPONG': 'JUICE_PONG',
        'STATISTIC_SKILL_ADULTMINOR_LOCALCULTURE': 'SELVADORADIAN_CULTURE',
        'STATISTIC_SKILL_ADULTMINOR_MEDIAPRODUCTION': 'MEDIA_PRODUCTION',
        'STATISTIC_SKILL_ADULTMINOR_MEDIUM': 'MEDIUM',
        'STATISTIC_SKILL_ADULTMINOR_PINGPONG': 'PING_PONG',
        'STATISTIC_SKILL_ADULTMINOR_RANCHNECTAR': 'RANCH_NECTAR',
        'STATISTIC_SKILL_ADULTMINOR_THANATOLOGY': 'THANATOLOGY',
        'STATISTIC_SKILL_BOWLING': 'BOWLING',
        'STATISTIC_SKILL_CHILD_CREATIVITY': 'CREATIVITY',
        'STATISTIC_SKILL_CHILD_MENTAL': 'MENTAL',
        'STATISTIC_SKILL_CHILD_MOTOR': 'MOTOR',
        'STATISTIC_SKILL_CHILD_SOCIAL': 'SOCIAL',
        'STATISTIC_SKILL_CROSSSTITCH': 'CROSS_STITCH',
        'STATISTIC_SKILL_DOGTRAINING': 'PET_TRAINING',
        'STATISTIC_SKILL_HIDDEN_CLASSROOMSHELL_TUTOR_PICKEDSKILL': 'SHELL_TUTOR_PICKED_SKILL_HIDDEN',
        'STATISTIC_SKILL_HIDDEN_INFANT_CRAWL': 'INFANT_CRAWL_HIDDEN',
        'STATISTIC_SKILL_HIDDEN_INFANT_SOCIAL_AGEUP': 'INFANT_SOCIAL_AGE_UP_HIDDEN',
        'STATISTIC_SKILL_HIDDEN_MILESTONE_INFANT_FINEMOTOR': 'INFANT_MILESTONE_FINE_MOTOR_HIDDEN',
        'STATISTIC_SKILL_HIDDEN_MILESTONE_INFANT_GROSSMOTOR': 'INFANT_MILESTONE_GROSS_MOTOR_HIDDEN',
        'STATISTIC_SKILL_HIDDEN_MILESTONE_INFANT_SOCIAL': 'INFANT_MILESTONE_SOCIAL_HIDDEN',
        'STATISTIC_SKILL_HIDDEN_SKATING': 'SKATING_HIDDEN',
        'STATISTIC_SKILL_HIDDEN_TREADMILL_ROCK_CLIMBINGWALL_CLIMB': 'ROCK_CLIMBING_HIDDEN',
        'STATISTIC_SKILL_HIDDEN_VAMPIRELORE': 'VAMPIRE_LORE_HIDDEN',
        'STATISTIC_SKILL_HORSE_AGILITY': 'HORSE_AGILITY',
        'STATISTIC_SKILL_HORSE_ENDURANCE': 'HORSE_ENDURANCE',
        'STATISTIC_SKILL_HORSE_JUMPING': 'HORSE_JUMPING',
        'STATISTIC_SKILL_HORSE_TEMPERAMENT': 'HORSE_TEMPERAMENT',
        'STATISTIC_SKILL_HUMANOIDROBOT_ENHANCEMENT': 'HUMANOID_ROBOT_ENHANCEMENT',
        'STATISTIC_SKILL_NLS': 'NATURAL_LIVING',
        'STATISTIC_SKILL_RETAIL_MAINTENANCE': 'MAINTENANCE',
        'STATISTIC_SKILL_RETAIL_SALES': 'SALES',
        'STATISTIC_SKILL_RETAIL_WORKETHIC': 'WORK_ETHIC',
        'STATISTIC_SKILL_TODDLER_COMMUNICATION': 'COMMUNICATION',
        'STATISTIC_SKILL_TODDLER_IMAGINATION': 'IMAGINATION',
        'STATISTIC_SKILL_TODDLER_MOVEMENT': 'MOVEMENT',
        'STATISTIC_SKILL_TODDLER_POTTY': 'POTTY',
        'STATISTIC_SKILL_TODDLER_THINKING': 'THINKING',
    }


@CommonConsoleCommand(ModInfo.get_identity(), 's4clib_dev.log_skills', 'Logs a list of skills and skill ids for easy transfer to CommonSkillId', show_with_help_command=False)
def _common_log_skills_ready_for_update(output: CommonConsoleCommandOutput) -> None:
    output('Logging Traits')
    from sims4communitylib_development._development._s4cl_enum_value_update_utils import _S4CLEnumValueUpdateUtils
    from sims4communitylib.enums.skills_enum import CommonSkillId
    # noinspection PyTypeChecker
    skills: Tuple[Any] = tuple(CommonSkillUtils.get_all_skills_gen())
    not_found_values = _S4CLEnumValueUpdateUtils()._read_values_from_instances(skills, _S4CLReaderForUpdate.CONVERSIONS, CommonSkillId, skip_not_found=True)
    output(f'Finished logging Traits. {len(not_found_values)} values were not found.')
