"""
The Sims 4 Community Library is licensed under the Creative Commons Attribution 4.0 International public license (CC BY 4.0).
https://creativecommons.org/licenses/by/4.0/
https://creativecommons.org/licenses/by/4.0/legalcode

Copyright (c) COLONOLNUTTY
"""


class CommonSlotType:
    """Slot types for various objects.

    """
    ACTIVITY_TABLE_PAINTING: 'CommonSlotType' = 'ActivityTablePainting'
    ANIMATION_SLOT_SIM_INTERACTION: 'CommonSlotType' = 'animationSlot_SimInteraction'
    ANIMATION_SLOT_SIT_INDIVIDUAL: 'CommonSlotType' = 'animationSlot_SitIndividual'
    ANIMATION_SLOT_SIT_SHARED: 'CommonSlotType' = 'animationSlot_SitShared'
    APPLIANCE_EMBEDDED: 'CommonSlotType' = 'ApplianceEmbedded'
    APPLIANCE_SURFACE: 'CommonSlotType' = 'ApplianceSurface'
    ARCHAEOLOGY_TABLE: 'CommonSlotType' = 'archaeologyTable'
    AUTO_PET_FEEDER: 'CommonSlotType' = 'AutoPetFeeder'
    BANQUET_TABLE_CENTER_PIECE: 'CommonSlotType' = 'BanquetTableCenterpiece'
    BAR_SERVE: 'CommonSlotType' = 'BarServe'
    BOOKSHELVES_E: 'CommonSlotType' = 'BookShelves_E'
    BOOKSHELVES_W: 'CommonSlotType' = 'BookShelves_W'
    BOOTH: 'CommonSlotType' = 'Booth'
    BOOTH_CORNER: 'CommonSlotType' = 'BoothCorner'
    BULLETIN_BOARD_CURFEW_DRAWING: 'CommonSlotType' = 'bulletinBoardCurfewDrawing'
    BULLETIN_BOARD_CURFEW_NOTE: 'CommonSlotType' = 'bulletinBoardCurfewNote'
    CAMERA_TRIPOD: 'CommonSlotType' = 'Camera_Tripod'
    CAMPFIRE_SIT: 'CommonSlotType' = 'CampfireSit'
    CARVING_STATION: 'CommonSlotType' = 'CarvingStation'
    CHEF_STATION_FOOD_PLATTER: 'CommonSlotType' = 'ChefStationFoodPlatter'
    CHEMISTRY_LAB_SCIENCE: 'CommonSlotType' = 'ChemistryLabScience'
    CLONING_MACHINE_CLONE: 'CommonSlotType' = 'CloningMachineClone'
    CLONING_MACHINE_SIM: 'CommonSlotType' = 'CloningMachineSim'
    CLONING_MACHINE_SOURCE: 'CommonSlotType' = 'CloningMachineSource'
    COLLECTION_SKULL_DISPLAY: 'CommonSlotType' = 'Collection_Skull_Display'
    COLLECT_MONSTER_BATTLE_CARD: 'CommonSlotType' = 'collectMonsterBattleCard'
    CRAFT_ROBOTICS: 'CommonSlotType' = 'CraftRobotics'
    CUPCAKE_MACHINE_SERVE: 'CommonSlotType' = 'CupcakeMachineServe'
    CURTAIN: 'CommonSlotType' = 'Curtain'
    DRINK_DECANTER: 'CommonSlotType' = 'DrinkDecanter'
    DRINK_TRAY_SERVE: 'CommonSlotType' = 'DrinkTrayServe'
    EASEL_PAINT: 'CommonSlotType' = 'EaselPaint'
    ESPRESSO_BAR_BREW: 'CommonSlotType' = 'espressoBarBrew'
    ESPRESSO_BAR_GRIND: 'CommonSlotType' = 'espressoBarGrind'
    ESPRESSO_MACHINE_CUP: 'CommonSlotType' = 'EspressoMachineCup'
    FENCE_DECO: 'CommonSlotType' = 'FenceDeco'
    FENCE_RAIL_SIDE_DECO: 'CommonSlotType' = 'FenceRailSideDeco'
    FLOOR_MURAL_PAINT: 'CommonSlotType' = 'FloorMuralPaint'
    FLOWER_ARRANGEMENT: 'CommonSlotType' = 'FlowerArrangement'
    GAMEPLAY_SLOT_DECO_LARGE: 'CommonSlotType' = '_gameplaySlot_Deco_Large'
    GAMEPLAY_SLOT_DECO_MEDIUM: 'CommonSlotType' = '_gameplaySlot_Deco_Medium'
    GAMEPLAY_SLOT_DECO_SMALL: 'CommonSlotType' = '_gameplaySlot_Deco_Small'
    GARAGE_MURAL_PAINT: 'CommonSlotType' = 'GarageMuralPaint'
    GLOBE_BAR_DECANTER: 'CommonSlotType' = 'GlobeBar_Decanter'
    GRILL_COOK: 'CommonSlotType' = 'GrillCook'
    HOLIDAY_TREE_DECORATION_GARLAND: 'CommonSlotType' = 'HolidayTree_Decoration_Garland'
    HOLIDAY_TREE_DECORATION_ORNAMENT: 'CommonSlotType' = 'HolidayTree_Decoration_Ornament'
    HOLIDAY_TREE_DECORATION_SKIRT: 'CommonSlotType' = 'HolidayTree_Decoration_Skirt'
    HOLIDAY_TREE_DECORATION_TOPPER: 'CommonSlotType' = 'HolidayTree_Decoration_Topper'
    HOLIDAY_TREE_PRESENT_PILE: 'CommonSlotType' = 'HolidayTree_PresentPile'
    HUMANOID_BOT: 'CommonSlotType' = 'humanoidBot'
    INVENTION_CONSTRUCTOR_SCIENCE: 'CommonSlotType' = 'InventionConstructorScience'
    JUICE_KEG_CUP: 'CommonSlotType' = 'JuiceKegCup'
    LAUNDRY_WASHING_MACHINE: 'CommonSlotType' = 'Laundry_WashingMachine'
    MAGIC_WAND_DISPLAY: 'CommonSlotType' = 'MagicWandDisplay'
    MECH_SUIT_HEAD: 'CommonSlotType' = 'MechSuitHead'
    MICROWAVE_COOK: 'CommonSlotType' = 'MicrowaveCook'
    MONSTER_BATTLE_SCREEN: 'CommonSlotType' = 'monsterBattleScreen'
    NIGHTSTAND: 'CommonSlotType' = 'Nightstand'
    OBJECT_SURFACE_2_X_1: 'CommonSlotType' = '2x1ObjectSurface'
    OFFERING: 'CommonSlotType' = 'Offering'
    OVEN_COOK: 'CommonSlotType' = 'OvenCook'
    PARTY_BOT: 'CommonSlotType' = 'PartyBot'
    PEDESTAL_STATUE: 'CommonSlotType' = 'PedestalStatue'
    PHOTO_COLLAGE_FRAME_LANDSCAPE_MED: 'CommonSlotType' = 'PhotoCollageFrame_Landscape_Med'
    PHOTO_COLLAGE_FRAME_LANDSCAPE_SMALL: 'CommonSlotType' = 'PhotoCollageFrame_Landscape_Small'
    PHOTO_COLLAGE_FRAME_PORTRAIT_MED: 'CommonSlotType' = 'PhotoCollageFrame_Portrait_Med'
    PHOTO_COLLAGE_FRAME_PORTRAIT_SMALL: 'CommonSlotType' = 'PhotoCollageFrame_Portrait_Small'
    PING_PONG_CUP: 'CommonSlotType' = 'PingPongCup'
    PLACEMAT_DRAWING: 'CommonSlotType' = 'PlacematDrawing'
    PLANT_COW: 'CommonSlotType' = 'PlantCow'
    PLANT_LARGE: 'CommonSlotType' = 'PlantLarge'
    PLANT_SIMS_MAGIC_BEANS: 'CommonSlotType' = 'PlantSims_MagicBeans'
    PLANT_SMALL: 'CommonSlotType' = 'PlantSmall'
    POSTCARD_BOARD_COLLECT: 'CommonSlotType' = 'PostcardBoardCollect'
    RESTAURANT_SIGN_DECAL_4_X_1_X_2: 'CommonSlotType' = 'RestaurantSignDecal4x1x2'
    RESTAURANT_SIGN_DECAL: 'CommonSlotType' = 'RestaurantSignDecal'
    RESTAURANT_SIGN_DECAL_LARGE: 'CommonSlotType' = 'RestaurantSignDecalLarge'
    RETAIL_FOOD_DISPLAY_SHOW: 'CommonSlotType' = 'RetailFoodDisplayShow'
    ROBOT_VACUUM: 'CommonSlotType' = 'RobotVacuum'
    ROLLUP_MURAL_PAINT: 'CommonSlotType' = 'RollupMuralPaint'
    SIT_CHAIR: 'CommonSlotType' = 'SitChair'
    SIT_CHAIR_LARGE: 'CommonSlotType' = 'SitChairLrg'
    SIT_CHAIR_TALL: 'CommonSlotType' = 'SitChairTall'
    SIT_DRINK: 'CommonSlotType' = 'SitDrink'
    SIT_EAT: 'CommonSlotType' = 'SitEat'
    SIT_INDIVIDUAL: 'CommonSlotType' = 'SitIndividual'
    SIT_SHARED: 'CommonSlotType' = 'SitShared'
    SPAWN_POINT: 'CommonSlotType' = 'SpawnPoint'
    STAGE: 'CommonSlotType' = 'Stage'
    STAND_INDIVIDUAL: 'CommonSlotType' = 'StandIndividual'
    STAND_SHARED: 'CommonSlotType' = 'StandShared'
    STAR_TILE: 'CommonSlotType' = 'starTile'
    STOVE_COOK: 'CommonSlotType' = 'StoveCook'
    STYLEBOARD: 'CommonSlotType' = 'Styleboard'
    SURGERY_TABLE_BASSINET: 'CommonSlotType' = 'SurgeryTable_Bassinet'
    TABLE_GAME_INDIVIDUAL: 'CommonSlotType' = 'TableGameIndividual'
    TABLE_GAME_SHARED: 'CommonSlotType' = 'TableGameShared'
    TODDLER_SIPPY_CUP: 'CommonSlotType' = 'ToddlerSippyCup'
    TV_STAND_TV: 'CommonSlotType' = 'TvStandTV'
    VIDEO_STATION: 'CommonSlotType' = 'VideoStation'
    WALL_MURAL_PAINT: 'CommonSlotType' = 'WallMuralPaint'
    WOODWORK_IN_PROGRESS: 'CommonSlotType' = 'WoodworkInProgress'
