"""
The Sims 4 Community Library is licensed under the Creative Commons Attribution 4.0 International public license (CC BY 4.0).
https://creativecommons.org/licenses/by/4.0/
https://creativecommons.org/licenses/by/4.0/legalcode

Copyright (c) COLONOLNUTTY
"""


class CommonSlotType:
    """ Slot types for various objects. """
    _2x1ObjectSurface: 'CommonSlotType' = '2x1ObjectSurface'
    _gameplaySlot_Deco_Large: 'CommonSlotType' = '_gameplaySlot_Deco_Large'
    _gameplaySlot_Deco_Medium: 'CommonSlotType' = '_gameplaySlot_Deco_Medium'
    _gameplaySlot_Deco_Small: 'CommonSlotType' = '_gameplaySlot_Deco_Small'
    ActivityTablePainting: 'CommonSlotType' = 'ActivityTablePainting'
    animationSlot_SimInteraction: 'CommonSlotType' = 'animationSlot_SimInteraction'
    animationSlot_SitIndividual: 'CommonSlotType' = 'animationSlot_SitIndividual'
    animationSlot_SitShared: 'CommonSlotType' = 'animationSlot_SitShared'
    ApplianceEmbedded: 'CommonSlotType' = 'ApplianceEmbedded'
    ApplianceSurface: 'CommonSlotType' = 'ApplianceSurface'
    archaeologyTable: 'CommonSlotType' = 'archaeologyTable'
    AutoPetFeeder: 'CommonSlotType' = 'AutoPetFeeder'
    BanquetTableCenterpiece: 'CommonSlotType' = 'BanquetTableCenterpiece'
    BarServe: 'CommonSlotType' = 'BarServe'
    BookShelves_E: 'CommonSlotType' = 'BookShelves_E'
    BookShelves_W: 'CommonSlotType' = 'BookShelves_W'
    Booth: 'CommonSlotType' = 'Booth'
    BoothCorner: 'CommonSlotType' = 'BoothCorner'
    bulletinBoardCurfewDrawing: 'CommonSlotType' = 'bulletinBoardCurfewDrawing'
    bulletinBoardCurfewNote: 'CommonSlotType' = 'bulletinBoardCurfewNote'
    Camera_Tripod: 'CommonSlotType' = 'Camera_Tripod'
    CampfireSit: 'CommonSlotType' = 'CampfireSit'
    CarvingStation: 'CommonSlotType' = 'CarvingStation'
    ChefStationFoodPlatter: 'CommonSlotType' = 'ChefStationFoodPlatter'
    ChemistryLabScience: 'CommonSlotType' = 'ChemistryLabScience'
    CloningMachineClone: 'CommonSlotType' = 'CloningMachineClone'
    CloningMachineSim: 'CommonSlotType' = 'CloningMachineSim'
    CloningMachineSource: 'CommonSlotType' = 'CloningMachineSource'
    Collection_Skull_Display: 'CommonSlotType' = 'Collection_Skull_Display'
    collectMonsterBattleCard: 'CommonSlotType' = 'collectMonsterBattleCard'
    CraftRobotics: 'CommonSlotType' = 'CraftRobotics'
    CupcakeMachineServe: 'CommonSlotType' = 'CupcakeMachineServe'
    Curtain: 'CommonSlotType' = 'Curtain'
    DrinkDecanter: 'CommonSlotType' = 'DrinkDecanter'
    DrinkTrayServe: 'CommonSlotType' = 'DrinkTrayServe'
    EaselPaint: 'CommonSlotType' = 'EaselPaint'
    espressoBarBrew: 'CommonSlotType' = 'espressoBarBrew'
    espressoBarGrind: 'CommonSlotType' = 'espressoBarGrind'
    EspressoMachineCup: 'CommonSlotType' = 'EspressoMachineCup'
    FenceDeco: 'CommonSlotType' = 'FenceDeco'
    FenceRailSideDeco: 'CommonSlotType' = 'FenceRailSideDeco'
    FloorMuralPaint: 'CommonSlotType' = 'FloorMuralPaint'
    FlowerArrangement: 'CommonSlotType' = 'FlowerArrangement'
    GarageMuralPaint: 'CommonSlotType' = 'GarageMuralPaint'
    GlobeBar_Decanter: 'CommonSlotType' = 'GlobeBar_Decanter'
    GrillCook: 'CommonSlotType' = 'GrillCook'
    HolidayTree_Decoration_Garland: 'CommonSlotType' = 'HolidayTree_Decoration_Garland'
    HolidayTree_Decoration_Ornament: 'CommonSlotType' = 'HolidayTree_Decoration_Ornament'
    HolidayTree_Decoration_Skirt: 'CommonSlotType' = 'HolidayTree_Decoration_Skirt'
    HolidayTree_Decoration_Topper: 'CommonSlotType' = 'HolidayTree_Decoration_Topper'
    HolidayTree_PresentPile: 'CommonSlotType' = 'HolidayTree_PresentPile'
    humanoidBot: 'CommonSlotType' = 'humanoidBot'
    InventionConstructorScience: 'CommonSlotType' = 'InventionConstructorScience'
    JuiceKegCup: 'CommonSlotType' = 'JuiceKegCup'
    Laundry_WashingMachine: 'CommonSlotType' = 'Laundry_WashingMachine'
    MagicWandDisplay: 'CommonSlotType' = 'MagicWandDisplay'
    MechSuitHead: 'CommonSlotType' = 'MechSuitHead'
    MicrowaveCook: 'CommonSlotType' = 'MicrowaveCook'
    monsterBattleScreen: 'CommonSlotType' = 'monsterBattleScreen'
    Nightstand: 'CommonSlotType' = 'Nightstand'
    Offering: 'CommonSlotType' = 'Offering'
    OvenCook: 'CommonSlotType' = 'OvenCook'
    PartyBot: 'CommonSlotType' = 'PartyBot'
    PedestalStatue: 'CommonSlotType' = 'PedestalStatue'
    PhotoCollageFrame_Landscape_Med: 'CommonSlotType' = 'PhotoCollageFrame_Landscape_Med'
    PhotoCollageFrame_Landscape_Small: 'CommonSlotType' = 'PhotoCollageFrame_Landscape_Small'
    PhotoCollageFrame_Portrait_Med: 'CommonSlotType' = 'PhotoCollageFrame_Portrait_Med'
    PhotoCollageFrame_Portrait_Small: 'CommonSlotType' = 'PhotoCollageFrame_Portrait_Small'
    PingPongCup: 'CommonSlotType' = 'PingPongCup'
    PlacematDrawing: 'CommonSlotType' = 'PlacematDrawing'
    PlantCow: 'CommonSlotType' = 'PlantCow'
    PlantLarge: 'CommonSlotType' = 'PlantLarge'
    PlantSims_MagicBeans: 'CommonSlotType' = 'PlantSims_MagicBeans'
    PlantSmall: 'CommonSlotType' = 'PlantSmall'
    PostcardBoardCollect: 'CommonSlotType' = 'PostcardBoardCollect'
    RestaurantSignDecal4x1x2: 'CommonSlotType' = 'RestaurantSignDecal4x1x2'
    RestaurantSignDecal: 'CommonSlotType' = 'RestaurantSignDecal'
    RestaurantSignDecalLarge: 'CommonSlotType' = 'RestaurantSignDecalLarge'
    RetailFoodDisplayShow: 'CommonSlotType' = 'RetailFoodDisplayShow'
    RobotVacuum: 'CommonSlotType' = 'RobotVacuum'
    RollupMuralPaint: 'CommonSlotType' = 'RollupMuralPaint'
    SitChair: 'CommonSlotType' = 'SitChair'
    SitChairLrg: 'CommonSlotType' = 'SitChairLrg'
    SitChairTall: 'CommonSlotType' = 'SitChairTall'
    SitDrink: 'CommonSlotType' = 'SitDrink'
    SitEat: 'CommonSlotType' = 'SitEat'
    SitIndividual: 'CommonSlotType' = 'SitIndividual'
    SitShared: 'CommonSlotType' = 'SitShared'
    SpawnPoint: 'CommonSlotType' = 'SpawnPoint'
    Stage: 'CommonSlotType' = 'Stage'
    StandIndividual: 'CommonSlotType' = 'StandIndividual'
    StandShared: 'CommonSlotType' = 'StandShared'
    starTile: 'CommonSlotType' = 'starTile'
    StoveCook: 'CommonSlotType' = 'StoveCook'
    Styleboard: 'CommonSlotType' = 'Styleboard'
    SurgeryTable_Bassinet: 'CommonSlotType' = 'SurgeryTable_Bassinet'
    TableGameIndividual: 'CommonSlotType' = 'TableGameIndividual'
    TableGameShared: 'CommonSlotType' = 'TableGameShared'
    ToddlerSippyCup: 'CommonSlotType' = 'ToddlerSippyCup'
    TvStandTV: 'CommonSlotType' = 'TvStandTV'
    VideoStation: 'CommonSlotType' = 'VideoStation'
    WallMuralPaint: 'CommonSlotType' = 'WallMuralPaint'
    WoodworkInProgress: 'CommonSlotType' = 'WoodworkInProgress'
