"""
The Sims 4 Community Library is licensed under the Creative Commons Attribution 4.0 International public license (CC BY 4.0).
https://creativecommons.org/licenses/by/4.0/
https://creativecommons.org/licenses/by/4.0/legalcode

Copyright (c) COLONOLNUTTY
"""
from sims4communitylib.enums.enumtypes.common_int import CommonInt


class CommonKey(CommonInt):
    """Keys and their Key Codes for various keys on the keyboard. Currently recognizes Windows and Mac keys."""
    INVALID: 'CommonKey' = -1
    # Windows Keys
    BACKSPACE: 'CommonKey' = 8
    TAB: 'CommonKey' = 9
    NUM_PAD_OFF_5: 'CommonKey' = 12
    ENTER: 'CommonKey' = 13
    SHIFT: 'CommonKey' = 16  # Can be used for both Left and Right SHIFT
    CTRL: 'CommonKey' = 17  # Can be used for both Left and Right CTRL
    ALT: 'CommonKey' = 18  # Can be used for both Left and Right ALT
    PAUSE: 'CommonKey' = 19
    CAPS_LOCK: 'CommonKey' = 20
    ESCAPE: 'CommonKey' = 27
    SPACE: 'CommonKey' = 32
    PAGE_UP: 'CommonKey' = 33
    PAGE_DOWN: 'CommonKey' = 34
    END: 'CommonKey' = 35
    HOME: 'CommonKey' = 36
    ARROW_LEFT: 'CommonKey' = 37
    ARROW_UP: 'CommonKey' = 38
    ARROW_RIGHT: 'CommonKey' = 39
    ARROW_DOWN: 'CommonKey' = 40
    SYSTEM_REQUEST: 'CommonKey' = 44
    INSERT: 'CommonKey' = 45
    DELETE: 'CommonKey' = 46
    KEY_0: 'CommonKey' = 48
    KEY_1: 'CommonKey' = 49
    KEY_2: 'CommonKey' = 50
    KEY_3: 'CommonKey' = 51
    KEY_4: 'CommonKey' = 52
    KEY_5: 'CommonKey' = 53
    KEY_6: 'CommonKey' = 54
    KEY_7: 'CommonKey' = 55
    KEY_8: 'CommonKey' = 56
    KEY_9: 'CommonKey' = 57
    KEY_A: 'CommonKey' = 65
    KEY_B: 'CommonKey' = 66
    KEY_C: 'CommonKey' = 67
    KEY_D: 'CommonKey' = 68
    KEY_E: 'CommonKey' = 69
    KEY_F: 'CommonKey' = 70
    KEY_G: 'CommonKey' = 71
    KEY_H: 'CommonKey' = 72
    KEY_I: 'CommonKey' = 73
    KEY_J: 'CommonKey' = 74
    KEY_K: 'CommonKey' = 75
    KEY_L: 'CommonKey' = 76
    KEY_M: 'CommonKey' = 77
    KEY_N: 'CommonKey' = 78
    KEY_O: 'CommonKey' = 79
    KEY_P: 'CommonKey' = 80
    KEY_Q: 'CommonKey' = 81
    KEY_R: 'CommonKey' = 82
    KEY_S: 'CommonKey' = 83
    KEY_T: 'CommonKey' = 84
    KEY_U: 'CommonKey' = 85
    KEY_V: 'CommonKey' = 86
    KEY_W: 'CommonKey' = 87
    KEY_X: 'CommonKey' = 88
    KEY_Y: 'CommonKey' = 89
    KEY_Z: 'CommonKey' = 90
    WINDOWS_LEFT: 'CommonKey' = 91
    WINDOWS_RIGHT: 'CommonKey' = 92
    APPLICATIONS: 'CommonKey' = 93
    NUM_PAD_0: 'CommonKey' = 96
    NUM_PAD_1: 'CommonKey' = 97
    NUM_PAD_2: 'CommonKey' = 98
    NUM_PAD_3: 'CommonKey' = 99
    NUM_PAD_4: 'CommonKey' = 100
    NUM_PAD_5: 'CommonKey' = 101
    NUM_PAD_6: 'CommonKey' = 102
    NUM_PAD_7: 'CommonKey' = 103
    NUM_PAD_8: 'CommonKey' = 104
    NUM_PAD_9: 'CommonKey' = 105
    NUM_PAD_MULTIPLY: 'CommonKey' = 106
    NUM_PAD_ADD: 'CommonKey' = 107
    NUM_PAD_SUBTRACT: 'CommonKey' = 109
    NUM_PAD_DECIMAL: 'CommonKey' = 110
    NUM_PAD_DIVIDE: 'CommonKey' = 111
    NUM_PAD_ENTER: 'CommonKey' = 13
    F1: 'CommonKey' = 112
    F2: 'CommonKey' = 113
    F3: 'CommonKey' = 114
    F4: 'CommonKey' = 115
    F5: 'CommonKey' = 116
    F6: 'CommonKey' = 117
    F7: 'CommonKey' = 118
    F8: 'CommonKey' = 119
    F9: 'CommonKey' = 120
    F10: 'CommonKey' = 121
    F11: 'CommonKey' = 122
    F12: 'CommonKey' = 123
    NUM_LOCK: 'CommonKey' = 144
    SCROLL_LOCK: 'CommonKey' = 145
    EQUAL: 'CommonKey' = 187
    SHIFT_LEFT: 'CommonKey' = 160
    SHIFT_RIGHT: 'CommonKey' = 161
    CTRL_LEFT: 'CommonKey' = 162
    CTRL_RIGHT: 'CommonKey' = 163
    ALT_LEFT: 'CommonKey' = 164
    ALT_RIGHT: 'CommonKey' = 165
    SEMICOLON: 'CommonKey' = 186
    COMMA: 'CommonKey' = 188
    SUBTRACT: 'CommonKey' = 189
    PERIOD: 'CommonKey' = 190
    FORWARD_SLASH: 'CommonKey' = 191
    BACK_SLASH: 'CommonKey' = 220
    TILDE: 'CommonKey' = 192
    SQUARE_BRACKET_LEFT: 'CommonKey' = 219
    SQUARE_BRACKET_RIGHT: 'CommonKey' = 221
    SINGLE_QUOTE: 'CommonKey' = 222

    # noinspection PyBroadException
    try:
        import os
        if os.name != 'nt':
            # Mac Keys
            BACKSPACE: 'CommonKey' = 51
            TAB: 'CommonKey' = 48
            ENTER: 'CommonKey' = 36
            SHIFT: 'CommonKey' = 56  # Left Shift since Mac does not have a common key code
            CTRL: 'CommonKey' = 55
            ALT: 'CommonKey' = 58  # Left Alt since Mac does not have a common key code
            CAPS_LOCK: 'CommonKey' = 57
            ESCAPE: 'CommonKey' = 53
            SPACE: 'CommonKey' = 49
            PAGE_UP: 'CommonKey' = 116
            PAGE_DOWN: 'CommonKey' = 121
            END: 'CommonKey' = 119
            HOME: 'CommonKey' = 115
            ARROW_LEFT: 'CommonKey' = 123
            ARROW_UP: 'CommonKey' = 126
            ARROW_RIGHT: 'CommonKey' = 124
            ARROW_DOWN: 'CommonKey' = 125
            INSERT: 'CommonKey' = -1  # No insert key on Mac
            DELETE: 'CommonKey' = 117
            KEY_0: 'CommonKey' = 29
            KEY_1: 'CommonKey' = 18
            KEY_2: 'CommonKey' = 19
            KEY_3: 'CommonKey' = 20
            KEY_4: 'CommonKey' = 21
            KEY_5: 'CommonKey' = 23
            KEY_6: 'CommonKey' = 22
            KEY_7: 'CommonKey' = 26
            KEY_8: 'CommonKey' = 28
            KEY_9: 'CommonKey' = 25
            KEY_A: 'CommonKey' = 0
            KEY_B: 'CommonKey' = 11
            KEY_C: 'CommonKey' = 8
            KEY_D: 'CommonKey' = 2
            KEY_E: 'CommonKey' = 14
            KEY_F: 'CommonKey' = 3
            KEY_G: 'CommonKey' = 5
            KEY_H: 'CommonKey' = 4
            KEY_I: 'CommonKey' = 34
            KEY_J: 'CommonKey' = 38
            KEY_K: 'CommonKey' = 40
            KEY_L: 'CommonKey' = 37
            KEY_M: 'CommonKey' = 46
            KEY_N: 'CommonKey' = 45
            KEY_O: 'CommonKey' = 31
            KEY_P: 'CommonKey' = 35
            KEY_Q: 'CommonKey' = 12
            KEY_R: 'CommonKey' = 15
            KEY_S: 'CommonKey' = 1
            KEY_T: 'CommonKey' = 17
            KEY_U: 'CommonKey' = 32
            KEY_V: 'CommonKey' = 9
            KEY_W: 'CommonKey' = 13
            KEY_Y: 'CommonKey' = 16
            KEY_X: 'CommonKey' = 7
            KEY_Z: 'CommonKey' = 6
            NUM_PAD_0: 'CommonKey' = 82
            NUM_PAD_1: 'CommonKey' = 83
            NUM_PAD_2: 'CommonKey' = 84
            NUM_PAD_3: 'CommonKey' = 85
            NUM_PAD_4: 'CommonKey' = 86
            NUM_PAD_5: 'CommonKey' = 87
            NUM_PAD_6: 'CommonKey' = 88
            NUM_PAD_7: 'CommonKey' = 89
            NUM_PAD_8: 'CommonKey' = 91
            NUM_PAD_9: 'CommonKey' = 92
            NUM_PAD_MULTIPLY: 'CommonKey' = 67
            NUM_PAD_ADD: 'CommonKey' = 69
            NUM_PAD_SUBTRACT: 'CommonKey' = 78
            NUM_PAD_DECIMAL: 'CommonKey' = 65
            NUM_PAD_DIVIDE: 'CommonKey' = 75
            NUM_PAD_ENTER: 'CommonKey' = 76
            F1: 'CommonKey' = 122
            F2: 'CommonKey' = 120
            F3: 'CommonKey' = 99
            F4: 'CommonKey' = 118
            F5: 'CommonKey' = 96
            F6: 'CommonKey' = 97
            F7: 'CommonKey' = 98
            F8: 'CommonKey' = 100
            F9: 'CommonKey' = 101
            F10: 'CommonKey' = 109
            F11: 'CommonKey' = 103
            F12: 'CommonKey' = 111
            EQUAL: 'CommonKey' = 24
            SHIFT_LEFT: 'CommonKey' = 56
            SHIFT_RIGHT: 'CommonKey' = 60
            CTRL_LEFT: 'CommonKey' = 55
            CTRL_RIGHT: 'CommonKey' = 55
            ALT_LEFT: 'CommonKey' = 58
            ALT_RIGHT: 'CommonKey' = 61
            SEMICOLON: 'CommonKey' = 41
            COMMA: 'CommonKey' = 43
            SUBTRACT: 'CommonKey' = 27
            PERIOD: 'CommonKey' = 47
            FORWARD_SLASH: 'CommonKey' = 44
            BACK_SLASH: 'CommonKey' = 42
            TILDE: 'CommonKey' = 50
            SQUARE_BRACKET_LEFT: 'CommonKey' = 33
            SQUARE_BRACKET_RIGHT: 'CommonKey' = 30
            SINGLE_QUOTE: 'CommonKey' = 39
    except:
        pass
