"""
The Sims 4 Community Library is licensed under the Creative Commons Attribution 4.0 International public license (CC BY 4.0).
https://creativecommons.org/licenses/by/4.0/
https://creativecommons.org/licenses/by/4.0/legalcode

Copyright (c) COLONOLNUTTY
"""
from typing import Tuple, Iterator

from sims4communitylib.enums.enumtypes.common_int_flags import CommonIntFlags


class CommonSimType(CommonIntFlags):
    """Various Sim Types that describe the Age, Species, and Occult Type of a Sim in a single value."""
    NONE: 'CommonSimType' = ...

    ELDER_HUMAN: 'CommonSimType' = ...
    ELDER_HUMAN_VAMPIRE: 'CommonSimType' = ...
    ELDER_HUMAN_GHOST: 'CommonSimType' = ...
    ELDER_HUMAN_ALIEN: 'CommonSimType' = ...
    ELDER_HUMAN_MERMAID: 'CommonSimType' = ...
    ELDER_HUMAN_WITCH: 'CommonSimType' = ...
    ELDER_HUMAN_ROBOT: 'CommonSimType' = ...
    ELDER_HUMAN_SCARECROW: 'CommonSimType' = ...
    ELDER_HUMAN_SKELETON: 'CommonSimType' = ...
    ELDER_HUMAN_PLANT_SIM: 'CommonSimType' = ...
    ELDER_HUMAN_WEREWOLF: 'CommonSimType' = ...
    ELDER_HUMAN_FAIRY: 'CommonSimType' = ...

    ADULT_HUMAN: 'CommonSimType' = ...
    ADULT_HUMAN_VAMPIRE: 'CommonSimType' = ...
    ADULT_HUMAN_GHOST: 'CommonSimType' = ...
    ADULT_HUMAN_ALIEN: 'CommonSimType' = ...
    ADULT_HUMAN_MERMAID: 'CommonSimType' = ...
    ADULT_HUMAN_WITCH: 'CommonSimType' = ...
    ADULT_HUMAN_ROBOT: 'CommonSimType' = ...
    ADULT_HUMAN_SCARECROW: 'CommonSimType' = ...
    ADULT_HUMAN_SKELETON: 'CommonSimType' = ...
    ADULT_HUMAN_PLANT_SIM: 'CommonSimType' = ...
    ADULT_HUMAN_WEREWOLF: 'CommonSimType' = ...
    ADULT_HUMAN_FAIRY: 'CommonSimType' = ...

    YOUNG_ADULT_HUMAN: 'CommonSimType' = ...
    YOUNG_ADULT_HUMAN_VAMPIRE: 'CommonSimType' = ...
    YOUNG_ADULT_HUMAN_GHOST: 'CommonSimType' = ...
    YOUNG_ADULT_HUMAN_ALIEN: 'CommonSimType' = ...
    YOUNG_ADULT_HUMAN_MERMAID: 'CommonSimType' = ...
    YOUNG_ADULT_HUMAN_WITCH: 'CommonSimType' = ...
    YOUNG_ADULT_HUMAN_ROBOT: 'CommonSimType' = ...
    YOUNG_ADULT_HUMAN_SCARECROW: 'CommonSimType' = ...
    YOUNG_ADULT_HUMAN_SKELETON: 'CommonSimType' = ...
    YOUNG_ADULT_HUMAN_PLANT_SIM: 'CommonSimType' = ...
    YOUNG_ADULT_HUMAN_WEREWOLF: 'CommonSimType' = ...
    YOUNG_ADULT_HUMAN_FAIRY: 'CommonSimType' = ...

    TEEN_HUMAN: 'CommonSimType' = ...
    TEEN_HUMAN_VAMPIRE: 'CommonSimType' = ...
    TEEN_HUMAN_GHOST: 'CommonSimType' = ...
    TEEN_HUMAN_ALIEN: 'CommonSimType' = ...
    TEEN_HUMAN_MERMAID: 'CommonSimType' = ...
    TEEN_HUMAN_WITCH: 'CommonSimType' = ...
    TEEN_HUMAN_ROBOT: 'CommonSimType' = ...
    TEEN_HUMAN_SCARECROW: 'CommonSimType' = ...
    TEEN_HUMAN_SKELETON: 'CommonSimType' = ...
    TEEN_HUMAN_PLANT_SIM: 'CommonSimType' = ...
    TEEN_HUMAN_WEREWOLF: 'CommonSimType' = ...
    TEEN_HUMAN_FAIRY: 'CommonSimType' = ...

    CHILD_HUMAN: 'CommonSimType' = ...
    CHILD_HUMAN_VAMPIRE: 'CommonSimType' = ...
    CHILD_HUMAN_GHOST: 'CommonSimType' = ...
    CHILD_HUMAN_ALIEN: 'CommonSimType' = ...
    CHILD_HUMAN_MERMAID: 'CommonSimType' = ...
    CHILD_HUMAN_WITCH: 'CommonSimType' = ...
    CHILD_HUMAN_ROBOT: 'CommonSimType' = ...
    CHILD_HUMAN_SCARECROW: 'CommonSimType' = ...
    CHILD_HUMAN_SKELETON: 'CommonSimType' = ...
    CHILD_HUMAN_PLANT_SIM: 'CommonSimType' = ...
    CHILD_HUMAN_WEREWOLF: 'CommonSimType' = ...
    CHILD_HUMAN_FAIRY: 'CommonSimType' = ...

    TODDLER_HUMAN: 'CommonSimType' = ...
    TODDLER_HUMAN_VAMPIRE: 'CommonSimType' = ...
    TODDLER_HUMAN_GHOST: 'CommonSimType' = ...
    TODDLER_HUMAN_ALIEN: 'CommonSimType' = ...
    TODDLER_HUMAN_MERMAID: 'CommonSimType' = ...
    TODDLER_HUMAN_WITCH: 'CommonSimType' = ...
    TODDLER_HUMAN_ROBOT: 'CommonSimType' = ...
    TODDLER_HUMAN_SCARECROW: 'CommonSimType' = ...
    TODDLER_HUMAN_SKELETON: 'CommonSimType' = ...
    TODDLER_HUMAN_PLANT_SIM: 'CommonSimType' = ...
    TODDLER_HUMAN_WEREWOLF: 'CommonSimType' = ...
    TODDLER_HUMAN_FAIRY: 'CommonSimType' = ...

    INFANT_HUMAN: 'CommonSimType' = ...
    INFANT_HUMAN_VAMPIRE: 'CommonSimType' = ...
    INFANT_HUMAN_GHOST: 'CommonSimType' = ...
    INFANT_HUMAN_ALIEN: 'CommonSimType' = ...
    INFANT_HUMAN_MERMAID: 'CommonSimType' = ...
    INFANT_HUMAN_WITCH: 'CommonSimType' = ...
    INFANT_HUMAN_ROBOT: 'CommonSimType' = ...
    INFANT_HUMAN_SCARECROW: 'CommonSimType' = ...
    INFANT_HUMAN_SKELETON: 'CommonSimType' = ...
    INFANT_HUMAN_PLANT_SIM: 'CommonSimType' = ...
    INFANT_HUMAN_WEREWOLF: 'CommonSimType' = ...
    INFANT_HUMAN_FAIRY: 'CommonSimType' = ...

    BABY_HUMAN: 'CommonSimType' = ...
    BABY_HUMAN_VAMPIRE: 'CommonSimType' = ...
    BABY_HUMAN_GHOST: 'CommonSimType' = ...
    BABY_HUMAN_ALIEN: 'CommonSimType' = ...
    BABY_HUMAN_MERMAID: 'CommonSimType' = ...
    BABY_HUMAN_WITCH: 'CommonSimType' = ...
    BABY_HUMAN_ROBOT: 'CommonSimType' = ...
    BABY_HUMAN_SCARECROW: 'CommonSimType' = ...
    BABY_HUMAN_SKELETON: 'CommonSimType' = ...
    BABY_HUMAN_PLANT_SIM: 'CommonSimType' = ...
    BABY_HUMAN_WEREWOLF: 'CommonSimType' = ...
    BABY_HUMAN_FAIRY: 'CommonSimType' = ...

    CHILD_DOG: 'CommonSimType' = ...
    CHILD_DOG_VAMPIRE: 'CommonSimType' = ...
    CHILD_DOG_GHOST: 'CommonSimType' = ...
    CHILD_DOG_ALIEN: 'CommonSimType' = ...
    CHILD_DOG_MERMAID: 'CommonSimType' = ...
    CHILD_DOG_WITCH: 'CommonSimType' = ...
    CHILD_DOG_ROBOT: 'CommonSimType' = ...
    CHILD_DOG_SCARECROW: 'CommonSimType' = ...
    CHILD_DOG_SKELETON: 'CommonSimType' = ...
    CHILD_DOG_PLANT_SIM: 'CommonSimType' = ...
    CHILD_DOG_WEREWOLF: 'CommonSimType' = ...
    CHILD_DOG_FAIRY: 'CommonSimType' = ...

    ELDER_SMALL_DOG: 'CommonSimType' = ...
    ELDER_SMALL_DOG_VAMPIRE: 'CommonSimType' = ...
    ELDER_SMALL_DOG_GHOST: 'CommonSimType' = ...
    ELDER_SMALL_DOG_ALIEN: 'CommonSimType' = ...
    ELDER_SMALL_DOG_MERMAID: 'CommonSimType' = ...
    ELDER_SMALL_DOG_WITCH: 'CommonSimType' = ...
    ELDER_SMALL_DOG_ROBOT: 'CommonSimType' = ...
    ELDER_SMALL_DOG_SCARECROW: 'CommonSimType' = ...
    ELDER_SMALL_DOG_SKELETON: 'CommonSimType' = ...
    ELDER_SMALL_DOG_PLANT_SIM: 'CommonSimType' = ...
    ELDER_SMALL_DOG_WEREWOLF: 'CommonSimType' = ...
    ELDER_SMALL_DOG_FAIRY: 'CommonSimType' = ...

    ADULT_SMALL_DOG: 'CommonSimType' = ...
    ADULT_SMALL_DOG_VAMPIRE: 'CommonSimType' = ...
    ADULT_SMALL_DOG_GHOST: 'CommonSimType' = ...
    ADULT_SMALL_DOG_ALIEN: 'CommonSimType' = ...
    ADULT_SMALL_DOG_MERMAID: 'CommonSimType' = ...
    ADULT_SMALL_DOG_WITCH: 'CommonSimType' = ...
    ADULT_SMALL_DOG_ROBOT: 'CommonSimType' = ...
    ADULT_SMALL_DOG_SCARECROW: 'CommonSimType' = ...
    ADULT_SMALL_DOG_SKELETON: 'CommonSimType' = ...
    ADULT_SMALL_DOG_PLANT_SIM: 'CommonSimType' = ...
    ADULT_SMALL_DOG_WEREWOLF: 'CommonSimType' = ...
    ADULT_SMALL_DOG_FAIRY: 'CommonSimType' = ...

    CHILD_SMALL_DOG: 'CommonSimType' = ...
    CHILD_SMALL_DOG_VAMPIRE: 'CommonSimType' = ...
    CHILD_SMALL_DOG_GHOST: 'CommonSimType' = ...
    CHILD_SMALL_DOG_ALIEN: 'CommonSimType' = ...
    CHILD_SMALL_DOG_MERMAID: 'CommonSimType' = ...
    CHILD_SMALL_DOG_WITCH: 'CommonSimType' = ...
    CHILD_SMALL_DOG_ROBOT: 'CommonSimType' = ...
    CHILD_SMALL_DOG_SCARECROW: 'CommonSimType' = ...
    CHILD_SMALL_DOG_SKELETON: 'CommonSimType' = ...
    CHILD_SMALL_DOG_PLANT_SIM: 'CommonSimType' = ...
    CHILD_SMALL_DOG_WEREWOLF: 'CommonSimType' = ...
    CHILD_SMALL_DOG_FAIRY: 'CommonSimType' = ...

    ELDER_LARGE_DOG: 'CommonSimType' = ...
    ELDER_LARGE_DOG_VAMPIRE: 'CommonSimType' = ...
    ELDER_LARGE_DOG_GHOST: 'CommonSimType' = ...
    ELDER_LARGE_DOG_ALIEN: 'CommonSimType' = ...
    ELDER_LARGE_DOG_MERMAID: 'CommonSimType' = ...
    ELDER_LARGE_DOG_WITCH: 'CommonSimType' = ...
    ELDER_LARGE_DOG_ROBOT: 'CommonSimType' = ...
    ELDER_LARGE_DOG_SCARECROW: 'CommonSimType' = ...
    ELDER_LARGE_DOG_SKELETON: 'CommonSimType' = ...
    ELDER_LARGE_DOG_PLANT_SIM: 'CommonSimType' = ...
    ELDER_LARGE_DOG_WEREWOLF: 'CommonSimType' = ...
    ELDER_LARGE_DOG_FAIRY: 'CommonSimType' = ...

    ADULT_LARGE_DOG: 'CommonSimType' = ...
    ADULT_LARGE_DOG_VAMPIRE: 'CommonSimType' = ...
    ADULT_LARGE_DOG_GHOST: 'CommonSimType' = ...
    ADULT_LARGE_DOG_ALIEN: 'CommonSimType' = ...
    ADULT_LARGE_DOG_MERMAID: 'CommonSimType' = ...
    ADULT_LARGE_DOG_WITCH: 'CommonSimType' = ...
    ADULT_LARGE_DOG_ROBOT: 'CommonSimType' = ...
    ADULT_LARGE_DOG_SCARECROW: 'CommonSimType' = ...
    ADULT_LARGE_DOG_SKELETON: 'CommonSimType' = ...
    ADULT_LARGE_DOG_PLANT_SIM: 'CommonSimType' = ...
    ADULT_LARGE_DOG_WEREWOLF: 'CommonSimType' = ...
    ADULT_LARGE_DOG_FAIRY: 'CommonSimType' = ...

    CHILD_LARGE_DOG: 'CommonSimType' = ...
    CHILD_LARGE_DOG_VAMPIRE: 'CommonSimType' = ...
    CHILD_LARGE_DOG_GHOST: 'CommonSimType' = ...
    CHILD_LARGE_DOG_ALIEN: 'CommonSimType' = ...
    CHILD_LARGE_DOG_MERMAID: 'CommonSimType' = ...
    CHILD_LARGE_DOG_WITCH: 'CommonSimType' = ...
    CHILD_LARGE_DOG_ROBOT: 'CommonSimType' = ...
    CHILD_LARGE_DOG_SCARECROW: 'CommonSimType' = ...
    CHILD_LARGE_DOG_SKELETON: 'CommonSimType' = ...
    CHILD_LARGE_DOG_PLANT_SIM: 'CommonSimType' = ...
    CHILD_LARGE_DOG_WEREWOLF: 'CommonSimType' = ...
    CHILD_LARGE_DOG_FAIRY: 'CommonSimType' = ...

    ELDER_CAT: 'CommonSimType' = ...
    ELDER_CAT_VAMPIRE: 'CommonSimType' = ...
    ELDER_CAT_GHOST: 'CommonSimType' = ...
    ELDER_CAT_ALIEN: 'CommonSimType' = ...
    ELDER_CAT_MERMAID: 'CommonSimType' = ...
    ELDER_CAT_WITCH: 'CommonSimType' = ...
    ELDER_CAT_ROBOT: 'CommonSimType' = ...
    ELDER_CAT_SCARECROW: 'CommonSimType' = ...
    ELDER_CAT_SKELETON: 'CommonSimType' = ...
    ELDER_CAT_PLANT_SIM: 'CommonSimType' = ...
    ELDER_CAT_WEREWOLF: 'CommonSimType' = ...
    ELDER_CAT_FAIRY: 'CommonSimType' = ...

    ADULT_CAT: 'CommonSimType' = ...
    ADULT_CAT_VAMPIRE: 'CommonSimType' = ...
    ADULT_CAT_GHOST: 'CommonSimType' = ...
    ADULT_CAT_ALIEN: 'CommonSimType' = ...
    ADULT_CAT_MERMAID: 'CommonSimType' = ...
    ADULT_CAT_WITCH: 'CommonSimType' = ...
    ADULT_CAT_ROBOT: 'CommonSimType' = ...
    ADULT_CAT_SCARECROW: 'CommonSimType' = ...
    ADULT_CAT_SKELETON: 'CommonSimType' = ...
    ADULT_CAT_PLANT_SIM: 'CommonSimType' = ...
    ADULT_CAT_WEREWOLF: 'CommonSimType' = ...
    ADULT_CAT_FAIRY: 'CommonSimType' = ...

    CHILD_CAT: 'CommonSimType' = ...
    CHILD_CAT_VAMPIRE: 'CommonSimType' = ...
    CHILD_CAT_GHOST: 'CommonSimType' = ...
    CHILD_CAT_ALIEN: 'CommonSimType' = ...
    CHILD_CAT_MERMAID: 'CommonSimType' = ...
    CHILD_CAT_WITCH: 'CommonSimType' = ...
    CHILD_CAT_ROBOT: 'CommonSimType' = ...
    CHILD_CAT_SCARECROW: 'CommonSimType' = ...
    CHILD_CAT_SKELETON: 'CommonSimType' = ...
    CHILD_CAT_PLANT_SIM: 'CommonSimType' = ...
    CHILD_CAT_WEREWOLF: 'CommonSimType' = ...
    CHILD_CAT_FAIRY: 'CommonSimType' = ...

    ELDER_FOX: 'CommonSimType' = ...
    ELDER_FOX_VAMPIRE: 'CommonSimType' = ...
    ELDER_FOX_GHOST: 'CommonSimType' = ...
    ELDER_FOX_ALIEN: 'CommonSimType' = ...
    ELDER_FOX_MERMAID: 'CommonSimType' = ...
    ELDER_FOX_WITCH: 'CommonSimType' = ...
    ELDER_FOX_ROBOT: 'CommonSimType' = ...
    ELDER_FOX_SCARECROW: 'CommonSimType' = ...
    ELDER_FOX_SKELETON: 'CommonSimType' = ...
    ELDER_FOX_PLANT_SIM: 'CommonSimType' = ...
    ELDER_FOX_WEREWOLF: 'CommonSimType' = ...
    ELDER_FOX_FAIRY: 'CommonSimType' = ...

    ADULT_FOX: 'CommonSimType' = ...
    ADULT_FOX_VAMPIRE: 'CommonSimType' = ...
    ADULT_FOX_GHOST: 'CommonSimType' = ...
    ADULT_FOX_ALIEN: 'CommonSimType' = ...
    ADULT_FOX_MERMAID: 'CommonSimType' = ...
    ADULT_FOX_WITCH: 'CommonSimType' = ...
    ADULT_FOX_ROBOT: 'CommonSimType' = ...
    ADULT_FOX_SCARECROW: 'CommonSimType' = ...
    ADULT_FOX_SKELETON: 'CommonSimType' = ...
    ADULT_FOX_PLANT_SIM: 'CommonSimType' = ...
    ADULT_FOX_WEREWOLF: 'CommonSimType' = ...
    ADULT_FOX_FAIRY: 'CommonSimType' = ...

    CHILD_FOX: 'CommonSimType' = ...
    CHILD_FOX_VAMPIRE: 'CommonSimType' = ...
    CHILD_FOX_GHOST: 'CommonSimType' = ...
    CHILD_FOX_ALIEN: 'CommonSimType' = ...
    CHILD_FOX_MERMAID: 'CommonSimType' = ...
    CHILD_FOX_WITCH: 'CommonSimType' = ...
    CHILD_FOX_ROBOT: 'CommonSimType' = ...
    CHILD_FOX_SCARECROW: 'CommonSimType' = ...
    CHILD_FOX_SKELETON: 'CommonSimType' = ...
    CHILD_FOX_PLANT_SIM: 'CommonSimType' = ...
    CHILD_FOX_WEREWOLF: 'CommonSimType' = ...
    CHILD_FOX_FAIRY: 'CommonSimType' = ...

    ELDER_HORSE: 'CommonSimType' = ...
    ELDER_HORSE_VAMPIRE: 'CommonSimType' = ...
    ELDER_HORSE_GHOST: 'CommonSimType' = ...
    ELDER_HORSE_ALIEN: 'CommonSimType' = ...
    ELDER_HORSE_MERMAID: 'CommonSimType' = ...
    ELDER_HORSE_WITCH: 'CommonSimType' = ...
    ELDER_HORSE_ROBOT: 'CommonSimType' = ...
    ELDER_HORSE_SCARECROW: 'CommonSimType' = ...
    ELDER_HORSE_SKELETON: 'CommonSimType' = ...
    ELDER_HORSE_PLANT_SIM: 'CommonSimType' = ...
    ELDER_HORSE_WEREWOLF: 'CommonSimType' = ...
    ELDER_HORSE_FAIRY: 'CommonSimType' = ...

    ADULT_HORSE: 'CommonSimType' = ...
    ADULT_HORSE_VAMPIRE: 'CommonSimType' = ...
    ADULT_HORSE_GHOST: 'CommonSimType' = ...
    ADULT_HORSE_ALIEN: 'CommonSimType' = ...
    ADULT_HORSE_MERMAID: 'CommonSimType' = ...
    ADULT_HORSE_WITCH: 'CommonSimType' = ...
    ADULT_HORSE_ROBOT: 'CommonSimType' = ...
    ADULT_HORSE_SCARECROW: 'CommonSimType' = ...
    ADULT_HORSE_SKELETON: 'CommonSimType' = ...
    ADULT_HORSE_PLANT_SIM: 'CommonSimType' = ...
    ADULT_HORSE_WEREWOLF: 'CommonSimType' = ...
    ADULT_HORSE_FAIRY: 'CommonSimType' = ...

    CHILD_HORSE: 'CommonSimType' = ...
    CHILD_HORSE_VAMPIRE: 'CommonSimType' = ...
    CHILD_HORSE_GHOST: 'CommonSimType' = ...
    CHILD_HORSE_ALIEN: 'CommonSimType' = ...
    CHILD_HORSE_MERMAID: 'CommonSimType' = ...
    CHILD_HORSE_WITCH: 'CommonSimType' = ...
    CHILD_HORSE_ROBOT: 'CommonSimType' = ...
    CHILD_HORSE_SCARECROW: 'CommonSimType' = ...
    CHILD_HORSE_SKELETON: 'CommonSimType' = ...
    CHILD_HORSE_PLANT_SIM: 'CommonSimType' = ...
    CHILD_HORSE_WEREWOLF: 'CommonSimType' = ...
    CHILD_HORSE_FAIRY: 'CommonSimType' = ...

    @classmethod
    def get_all(cls, include_teen_young_adult_and_elder: bool = False, include_baby: bool = False, include_infant: bool = False, include_separate_child_dog_types: bool = False, exclude_values: Iterator['CommonSimType'] = None) -> Tuple['CommonSimType']:
        """get_all(include_teen_young_adult_and_elder=False, include_baby=False, include_infant=False, include_separate_child_dog_types=False, exclude_values=None)

        Retrieve a collection of all Sim Types.

        :param include_teen_young_adult_and_elder: If set to True, the TEEN, YOUNG_ADULT, and ELDER Sim Types will be returned. If False, they will be excluded. Default is False.
        :type include_teen_young_adult_and_elder: bool, optional
        :param include_baby: If set to True, the BABY Sim Type will be included in the result. If False, the BABY Sim Type will not be included. Default is False.
        :type include_baby: bool, optional
        :param include_infant: If set to True, the INFANT Sim Type will be included in the result. If False, the INFANT Sim Type will not be included. Default is False.
        :type include_infant: bool, optional
        :param include_separate_child_dog_types: If set to True, the Child Dog Sim Types (CHILD_LARGE_DOG, CHILD_SMALL_DOG, etc.) will be included in the result. If False, they will not be included. Default is False.
        :type include_separate_child_dog_types: bool, optional
        :param exclude_values: These values will be excluded. If set to None, NONE will be excluded automatically. Default is None.
        :type exclude_values: Iterator[CommonSimType], optional
        :return: A collection of all Sim Types.
        :rtype: Tuple[CommonSimType]
        """
        if exclude_values is None:
            exclude_values = (cls.NONE,)
        sim_types: Tuple[CommonSimType, ...] = (
            CommonSimType.ADULT_HUMAN,
            CommonSimType.ADULT_HUMAN_VAMPIRE,
            CommonSimType.ADULT_HUMAN_GHOST,
            CommonSimType.ADULT_HUMAN_ALIEN,
            CommonSimType.ADULT_HUMAN_MERMAID,
            CommonSimType.ADULT_HUMAN_WITCH,
            CommonSimType.ADULT_HUMAN_ROBOT,
            CommonSimType.ADULT_HUMAN_SCARECROW,
            CommonSimType.ADULT_HUMAN_SKELETON,
            CommonSimType.ADULT_HUMAN_PLANT_SIM,
            CommonSimType.ADULT_HUMAN_WEREWOLF,
            CommonSimType.ADULT_HUMAN_FAIRY,

            CommonSimType.CHILD_HUMAN,
            CommonSimType.CHILD_HUMAN_VAMPIRE,
            CommonSimType.CHILD_HUMAN_GHOST,
            CommonSimType.CHILD_HUMAN_ALIEN,
            CommonSimType.CHILD_HUMAN_MERMAID,
            CommonSimType.CHILD_HUMAN_WITCH,
            CommonSimType.CHILD_HUMAN_ROBOT,
            CommonSimType.CHILD_HUMAN_SCARECROW,
            CommonSimType.CHILD_HUMAN_SKELETON,
            CommonSimType.CHILD_HUMAN_PLANT_SIM,
            CommonSimType.CHILD_HUMAN_WEREWOLF,
            CommonSimType.CHILD_HUMAN_FAIRY,

            CommonSimType.TODDLER_HUMAN,
            CommonSimType.TODDLER_HUMAN_VAMPIRE,
            CommonSimType.TODDLER_HUMAN_GHOST,
            CommonSimType.TODDLER_HUMAN_ALIEN,
            CommonSimType.TODDLER_HUMAN_MERMAID,
            CommonSimType.TODDLER_HUMAN_WITCH,
            CommonSimType.TODDLER_HUMAN_ROBOT,
            CommonSimType.TODDLER_HUMAN_SCARECROW,
            CommonSimType.TODDLER_HUMAN_SKELETON,
            CommonSimType.TODDLER_HUMAN_PLANT_SIM,
            CommonSimType.TODDLER_HUMAN_WEREWOLF,
            CommonSimType.TODDLER_HUMAN_FAIRY,

            CommonSimType.ADULT_SMALL_DOG,
            CommonSimType.ADULT_SMALL_DOG_VAMPIRE,
            CommonSimType.ADULT_SMALL_DOG_GHOST,
            CommonSimType.ADULT_SMALL_DOG_ALIEN,
            CommonSimType.ADULT_SMALL_DOG_MERMAID,
            CommonSimType.ADULT_SMALL_DOG_WITCH,
            CommonSimType.ADULT_SMALL_DOG_ROBOT,
            CommonSimType.ADULT_SMALL_DOG_SCARECROW,
            CommonSimType.ADULT_SMALL_DOG_SKELETON,
            CommonSimType.ADULT_SMALL_DOG_PLANT_SIM,
            CommonSimType.ADULT_SMALL_DOG_WEREWOLF,
            CommonSimType.ADULT_SMALL_DOG_FAIRY,

            CommonSimType.ADULT_LARGE_DOG,
            CommonSimType.ADULT_LARGE_DOG_VAMPIRE,
            CommonSimType.ADULT_LARGE_DOG_GHOST,
            CommonSimType.ADULT_LARGE_DOG_ALIEN,
            CommonSimType.ADULT_LARGE_DOG_MERMAID,
            CommonSimType.ADULT_LARGE_DOG_WITCH,
            CommonSimType.ADULT_LARGE_DOG_ROBOT,
            CommonSimType.ADULT_LARGE_DOG_SCARECROW,
            CommonSimType.ADULT_LARGE_DOG_SKELETON,
            CommonSimType.ADULT_LARGE_DOG_PLANT_SIM,
            CommonSimType.ADULT_LARGE_DOG_WEREWOLF,
            CommonSimType.ADULT_LARGE_DOG_FAIRY,

            CommonSimType.ADULT_CAT,
            CommonSimType.ADULT_CAT_VAMPIRE,
            CommonSimType.ADULT_CAT_GHOST,
            CommonSimType.ADULT_CAT_ALIEN,
            CommonSimType.ADULT_CAT_MERMAID,
            CommonSimType.ADULT_CAT_WITCH,
            CommonSimType.ADULT_CAT_ROBOT,
            CommonSimType.ADULT_CAT_SCARECROW,
            CommonSimType.ADULT_CAT_SKELETON,
            CommonSimType.ADULT_CAT_PLANT_SIM,
            CommonSimType.ADULT_CAT_WEREWOLF,
            CommonSimType.ADULT_CAT_FAIRY,

            CommonSimType.CHILD_CAT,
            CommonSimType.CHILD_CAT_VAMPIRE,
            CommonSimType.CHILD_CAT_GHOST,
            CommonSimType.CHILD_CAT_ALIEN,
            CommonSimType.CHILD_CAT_MERMAID,
            CommonSimType.CHILD_CAT_WITCH,
            CommonSimType.CHILD_CAT_ROBOT,
            CommonSimType.CHILD_CAT_SCARECROW,
            CommonSimType.CHILD_CAT_SKELETON,
            CommonSimType.CHILD_CAT_PLANT_SIM,
            CommonSimType.CHILD_CAT_WEREWOLF,
            CommonSimType.CHILD_CAT_FAIRY,

            CommonSimType.ADULT_FOX,
            CommonSimType.ADULT_FOX_VAMPIRE,
            CommonSimType.ADULT_FOX_GHOST,
            CommonSimType.ADULT_FOX_ALIEN,
            CommonSimType.ADULT_FOX_MERMAID,
            CommonSimType.ADULT_FOX_WITCH,
            CommonSimType.ADULT_FOX_ROBOT,
            CommonSimType.ADULT_FOX_SCARECROW,
            CommonSimType.ADULT_FOX_SKELETON,
            CommonSimType.ADULT_FOX_PLANT_SIM,
            CommonSimType.ADULT_FOX_WEREWOLF,
            CommonSimType.ADULT_FOX_FAIRY,

            CommonSimType.CHILD_FOX,
            CommonSimType.CHILD_FOX_VAMPIRE,
            CommonSimType.CHILD_FOX_GHOST,
            CommonSimType.CHILD_FOX_ALIEN,
            CommonSimType.CHILD_FOX_MERMAID,
            CommonSimType.CHILD_FOX_WITCH,
            CommonSimType.CHILD_FOX_ROBOT,
            CommonSimType.CHILD_FOX_SCARECROW,
            CommonSimType.CHILD_FOX_SKELETON,
            CommonSimType.CHILD_FOX_PLANT_SIM,
            CommonSimType.CHILD_FOX_WEREWOLF,
            CommonSimType.CHILD_FOX_FAIRY,

            CommonSimType.CHILD_DOG,
            CommonSimType.CHILD_DOG_VAMPIRE,
            CommonSimType.CHILD_DOG_GHOST,
            CommonSimType.CHILD_DOG_ALIEN,
            CommonSimType.CHILD_DOG_MERMAID,
            CommonSimType.CHILD_DOG_WITCH,
            CommonSimType.CHILD_DOG_ROBOT,
            CommonSimType.CHILD_DOG_SCARECROW,
            CommonSimType.CHILD_DOG_SKELETON,
            CommonSimType.CHILD_DOG_PLANT_SIM,
            CommonSimType.CHILD_DOG_WEREWOLF,
            CommonSimType.CHILD_DOG_FAIRY,

            CommonSimType.ADULT_HORSE,
            CommonSimType.ADULT_HORSE_VAMPIRE,
            CommonSimType.ADULT_HORSE_GHOST,
            CommonSimType.ADULT_HORSE_ALIEN,
            CommonSimType.ADULT_HORSE_MERMAID,
            CommonSimType.ADULT_HORSE_WITCH,
            CommonSimType.ADULT_HORSE_ROBOT,
            CommonSimType.ADULT_HORSE_SCARECROW,
            CommonSimType.ADULT_HORSE_SKELETON,
            CommonSimType.ADULT_HORSE_PLANT_SIM,
            CommonSimType.ADULT_HORSE_WEREWOLF,
            CommonSimType.ADULT_HORSE_FAIRY,

            CommonSimType.CHILD_HORSE,
            CommonSimType.CHILD_HORSE_VAMPIRE,
            CommonSimType.CHILD_HORSE_GHOST,
            CommonSimType.CHILD_HORSE_ALIEN,
            CommonSimType.CHILD_HORSE_MERMAID,
            CommonSimType.CHILD_HORSE_WITCH,
            CommonSimType.CHILD_HORSE_ROBOT,
            CommonSimType.CHILD_HORSE_SCARECROW,
            CommonSimType.CHILD_HORSE_SKELETON,
            CommonSimType.CHILD_HORSE_PLANT_SIM,
            CommonSimType.CHILD_HORSE_WEREWOLF,
            CommonSimType.CHILD_HORSE_FAIRY,
        )
        if include_teen_young_adult_and_elder:
            sim_types: Tuple[CommonSimType, ...] = (
                *sim_types,
                CommonSimType.ELDER_HUMAN,
                CommonSimType.ELDER_HUMAN_VAMPIRE,
                CommonSimType.ELDER_HUMAN_GHOST,
                CommonSimType.ELDER_HUMAN_ALIEN,
                CommonSimType.ELDER_HUMAN_MERMAID,
                CommonSimType.ELDER_HUMAN_WITCH,
                CommonSimType.ELDER_HUMAN_ROBOT,
                CommonSimType.ELDER_HUMAN_SCARECROW,
                CommonSimType.ELDER_HUMAN_SKELETON,
                CommonSimType.ELDER_HUMAN_PLANT_SIM,
                CommonSimType.ELDER_HUMAN_WEREWOLF,
                CommonSimType.ELDER_HUMAN_FAIRY,

                CommonSimType.YOUNG_ADULT_HUMAN,
                CommonSimType.YOUNG_ADULT_HUMAN_VAMPIRE,
                CommonSimType.YOUNG_ADULT_HUMAN_GHOST,
                CommonSimType.YOUNG_ADULT_HUMAN_ALIEN,
                CommonSimType.YOUNG_ADULT_HUMAN_MERMAID,
                CommonSimType.YOUNG_ADULT_HUMAN_WITCH,
                CommonSimType.YOUNG_ADULT_HUMAN_ROBOT,
                CommonSimType.YOUNG_ADULT_HUMAN_SCARECROW,
                CommonSimType.YOUNG_ADULT_HUMAN_SKELETON,
                CommonSimType.YOUNG_ADULT_HUMAN_PLANT_SIM,
                CommonSimType.YOUNG_ADULT_HUMAN_WEREWOLF,
                CommonSimType.YOUNG_ADULT_HUMAN_FAIRY,

                CommonSimType.TEEN_HUMAN,
                CommonSimType.TEEN_HUMAN_VAMPIRE,
                CommonSimType.TEEN_HUMAN_GHOST,
                CommonSimType.TEEN_HUMAN_ALIEN,
                CommonSimType.TEEN_HUMAN_MERMAID,
                CommonSimType.TEEN_HUMAN_WITCH,
                CommonSimType.TEEN_HUMAN_ROBOT,
                CommonSimType.TEEN_HUMAN_SCARECROW,
                CommonSimType.TEEN_HUMAN_SKELETON,
                CommonSimType.TEEN_HUMAN_PLANT_SIM,
                CommonSimType.TEEN_HUMAN_WEREWOLF,
                CommonSimType.TEEN_HUMAN_FAIRY,

                CommonSimType.ELDER_SMALL_DOG,
                CommonSimType.ELDER_SMALL_DOG_VAMPIRE,
                CommonSimType.ELDER_SMALL_DOG_GHOST,
                CommonSimType.ELDER_SMALL_DOG_ALIEN,
                CommonSimType.ELDER_SMALL_DOG_MERMAID,
                CommonSimType.ELDER_SMALL_DOG_WITCH,
                CommonSimType.ELDER_SMALL_DOG_ROBOT,
                CommonSimType.ELDER_SMALL_DOG_SCARECROW,
                CommonSimType.ELDER_SMALL_DOG_SKELETON,
                CommonSimType.ELDER_SMALL_DOG_PLANT_SIM,
                CommonSimType.ELDER_SMALL_DOG_WEREWOLF,
                CommonSimType.ELDER_SMALL_DOG_FAIRY,

                CommonSimType.ELDER_LARGE_DOG,
                CommonSimType.ELDER_LARGE_DOG_VAMPIRE,
                CommonSimType.ELDER_LARGE_DOG_GHOST,
                CommonSimType.ELDER_LARGE_DOG_ALIEN,
                CommonSimType.ELDER_LARGE_DOG_MERMAID,
                CommonSimType.ELDER_LARGE_DOG_WITCH,
                CommonSimType.ELDER_LARGE_DOG_ROBOT,
                CommonSimType.ELDER_LARGE_DOG_SCARECROW,
                CommonSimType.ELDER_LARGE_DOG_SKELETON,
                CommonSimType.ELDER_LARGE_DOG_PLANT_SIM,
                CommonSimType.ELDER_LARGE_DOG_WEREWOLF,
                CommonSimType.ELDER_LARGE_DOG_FAIRY,

                CommonSimType.ELDER_CAT,
                CommonSimType.ELDER_CAT_VAMPIRE,
                CommonSimType.ELDER_CAT_GHOST,
                CommonSimType.ELDER_CAT_ALIEN,
                CommonSimType.ELDER_CAT_MERMAID,
                CommonSimType.ELDER_CAT_WITCH,
                CommonSimType.ELDER_CAT_ROBOT,
                CommonSimType.ELDER_CAT_SCARECROW,
                CommonSimType.ELDER_CAT_SKELETON,
                CommonSimType.ELDER_CAT_PLANT_SIM,
                CommonSimType.ELDER_CAT_WEREWOLF,
                CommonSimType.ELDER_CAT_FAIRY,

                CommonSimType.ELDER_FOX,
                CommonSimType.ELDER_FOX_VAMPIRE,
                CommonSimType.ELDER_FOX_GHOST,
                CommonSimType.ELDER_FOX_ALIEN,
                CommonSimType.ELDER_FOX_MERMAID,
                CommonSimType.ELDER_FOX_WITCH,
                CommonSimType.ELDER_FOX_ROBOT,
                CommonSimType.ELDER_FOX_SCARECROW,
                CommonSimType.ELDER_FOX_SKELETON,
                CommonSimType.ELDER_FOX_PLANT_SIM,
                CommonSimType.ELDER_FOX_WEREWOLF,
                CommonSimType.ELDER_FOX_FAIRY,

                CommonSimType.ELDER_HORSE,
                CommonSimType.ELDER_HORSE_VAMPIRE,
                CommonSimType.ELDER_HORSE_GHOST,
                CommonSimType.ELDER_HORSE_ALIEN,
                CommonSimType.ELDER_HORSE_MERMAID,
                CommonSimType.ELDER_HORSE_WITCH,
                CommonSimType.ELDER_HORSE_ROBOT,
                CommonSimType.ELDER_HORSE_SCARECROW,
                CommonSimType.ELDER_HORSE_SKELETON,
                CommonSimType.ELDER_HORSE_PLANT_SIM,
                CommonSimType.ELDER_HORSE_WEREWOLF,
                CommonSimType.ELDER_HORSE_FAIRY,
            )
        if include_baby:
            sim_types: Tuple[CommonSimType, ...] = (
                *sim_types,
                CommonSimType.BABY_HUMAN,
                CommonSimType.BABY_HUMAN_VAMPIRE,
                CommonSimType.BABY_HUMAN_GHOST,
                CommonSimType.BABY_HUMAN_ALIEN,
                CommonSimType.BABY_HUMAN_MERMAID,
                CommonSimType.BABY_HUMAN_WITCH,
                CommonSimType.BABY_HUMAN_ROBOT,
                CommonSimType.BABY_HUMAN_SCARECROW,
                CommonSimType.BABY_HUMAN_SKELETON,
                CommonSimType.BABY_HUMAN_PLANT_SIM,
                CommonSimType.BABY_HUMAN_WEREWOLF,
                CommonSimType.BABY_HUMAN_FAIRY,
            )
        if include_infant:
            sim_types: Tuple[CommonSimType, ...] = (
                *sim_types,
                CommonSimType.INFANT_HUMAN,
                CommonSimType.INFANT_HUMAN_VAMPIRE,
                CommonSimType.INFANT_HUMAN_GHOST,
                CommonSimType.INFANT_HUMAN_ALIEN,
                CommonSimType.INFANT_HUMAN_MERMAID,
                CommonSimType.INFANT_HUMAN_WITCH,
                CommonSimType.INFANT_HUMAN_ROBOT,
                CommonSimType.INFANT_HUMAN_SCARECROW,
                CommonSimType.INFANT_HUMAN_SKELETON,
                CommonSimType.INFANT_HUMAN_PLANT_SIM,
                CommonSimType.INFANT_HUMAN_WEREWOLF,
                CommonSimType.INFANT_HUMAN_FAIRY,
            )
        if include_separate_child_dog_types:
            sim_types: Tuple[CommonSimType, ...] = (
                *sim_types,
                CommonSimType.CHILD_SMALL_DOG,
                CommonSimType.CHILD_SMALL_DOG_VAMPIRE,
                CommonSimType.CHILD_SMALL_DOG_GHOST,
                CommonSimType.CHILD_SMALL_DOG_ALIEN,
                CommonSimType.CHILD_SMALL_DOG_MERMAID,
                CommonSimType.CHILD_SMALL_DOG_WITCH,
                CommonSimType.CHILD_SMALL_DOG_ROBOT,
                CommonSimType.CHILD_SMALL_DOG_SCARECROW,
                CommonSimType.CHILD_SMALL_DOG_SKELETON,
                CommonSimType.CHILD_SMALL_DOG_PLANT_SIM,
                CommonSimType.CHILD_SMALL_DOG_WEREWOLF,
                CommonSimType.CHILD_SMALL_DOG_FAIRY,

                CommonSimType.CHILD_LARGE_DOG,
                CommonSimType.CHILD_LARGE_DOG_VAMPIRE,
                CommonSimType.CHILD_LARGE_DOG_GHOST,
                CommonSimType.CHILD_LARGE_DOG_ALIEN,
                CommonSimType.CHILD_LARGE_DOG_MERMAID,
                CommonSimType.CHILD_LARGE_DOG_WITCH,
                CommonSimType.CHILD_LARGE_DOG_ROBOT,
                CommonSimType.CHILD_LARGE_DOG_SCARECROW,
                CommonSimType.CHILD_LARGE_DOG_SKELETON,
                CommonSimType.CHILD_LARGE_DOG_PLANT_SIM,
                CommonSimType.CHILD_LARGE_DOG_WEREWOLF,
                CommonSimType.CHILD_LARGE_DOG_FAIRY,
            )
        # noinspection PyTypeChecker
        value_list: Tuple[CommonSimType] = tuple([value for value in sim_types if value not in exclude_values])
        return value_list
