"""
The Sims 4 Community Library is licensed under the Creative Commons Attribution 4.0 International public license (CC BY 4.0).
https://creativecommons.org/licenses/by/4.0/
https://creativecommons.org/licenses/by/4.0/legalcode

Copyright (c) COLONOLNUTTY
"""
from sims4.commands import Command, CommandType, CheatOutput
from sims4.resources import Types
from sims4communitylib.modinfo import ModInfo
from sims4communitylib.utils.common_log_registry import CommonLogRegistry


class _S4CLReaderForUpdate:
    # noinspection SpellCheckingInspection
    CONVERSIONS = {
        'CAREERS_ADULT_ACTIVIST': 'ACTIVIST',
        'CAREERS_ADULT_CIVILDESIGNER': 'CIVIL_DESIGNER',
        'CAREERS_ADULT_CONSERVATIONIST': 'CONSERVATIONIST',
        'CAREERS_ADULT_CORPORATEWORKER': 'CORPORATE_WORKER',
        'CAREERS_ADULT_CRITIC': 'CRITIC',
        'CAREERS_ADULT_EDUCATION': 'EDUCATION',
        'CAREERS_ADULT_ENGINEER': 'ENGINEER',
        'CAREERS_ADULT_FREELANCER_AGENCY_FASHION_PHOTOGRAPHER': 'FREELANCER_WITH_AGENCY_FASHION_PHOTOGRAPHER',
        'CAREERS_ADULT_FREELANCER_AGENCY_MAKER': 'FREELANCER_WITH_AGENCY_MAKER',
        'CAREERS_ADULT_FREELANCER_AGENCY_PARANORMALINVESTIGATOR': 'FREELANCER_WITH_AGENCY_PARANORMAL_INVESTIGATOR',
        'CAREERS_ADULT_FREELANCER_AGENCY_PROGRAMMER': 'FREELANCER_WITH_AGENCY_PROGRAMMER',
        'CAREERS_ADULT_FREELANCER_AGENCY_WRITER': 'FREELANCER_WITH_AGENCY_WRITER',
        'CAREERS_ADULT_FREELANCER_NO_AGENCY': 'FREELANCER_WITH_AGENCY_NONE',
        'CAREERS_ADULT_GARDENER': 'GARDENER',
        'CAREERS_ADULT_INTERIORDECORATOR': 'INTERIOR_DECORATOR',
        'CAREERS_ADULT_LAW': 'LAW',
        'CAREERS_ADULT_MILITARY': 'MILITARY',
        'CAREERS_ADULT_SOCIALMEDIA': 'SOCIAL_MEDIA',
        'CAREERS_VILLAGERHELP': 'COTTAGE_WORLD_VILLAGER_HELP',
        'CAREERS_VOLUNTEER_SOCCERTEAM': 'VOLUNTEER_SOCCER_TEAM',
        'CAREER_ADULT_ACTIVE_ACTORCAREER': 'ACTIVE_ACTOR',
        'CAREER_ADULT_ACTIVE_DOCTOR': 'ACTIVE_DOCTOR',
        'CAREER_ADULT_ACTIVE_SCIENTIST': 'ACTIVE_SCIENTIST',
        'CAREER_ADULT_ASTRONAUT': 'ASTRONAUT',
        'CAREER_ADULT_ATHLETIC': 'ATHLETIC',
        'CAREER_ADULT_BUSINESS': 'BUSINESS',
        'CAREER_ADULT_COTTAGEWORLD_NPC_GARDENSHOPOWNER': 'NPC_COTTAGE_WORLD_GARDEN_SHOP_OWNER',
        'CAREER_ADULT_COTTAGEWORLD_NPC_GROCERYDELIVERY': 'NPC_COTTAGE_WORLD_GROCERY_STORE_DELIVERY',
        'CAREER_ADULT_COTTAGEWORLD_NPC_GROCERYOWNER': 'NPC_COTTAGE_WORLD_GROCERY_STORE_OWNER',
        'CAREER_ADULT_COTTAGEWORLD_NPC_MAYOR': 'NPC_VENUE_MAYOR',
        'CAREER_ADULT_COTTAGEWORLD_NPC_PUBOWNER': 'NPC_VENUE_PUB_OWNER',
        'CAREER_ADULT_CRIMINAL': 'CRIMINAL',
        'CAREER_ADULT_CULINARY': 'CULINARY',
        'CAREER_ADULT_ENTERTAINER': 'ENTERTAINER',
        'CAREER_ADULT_FREELANCER_ARTIST': 'FREELANCER_WITH_AGENCY_ARTIST',
        'CAREER_ADULT_NPC_ADOPTIONOFFICER': 'NPC_SPECIAL_ADOPTION_OFFICER',
        'CAREER_ADULT_NPC_BARISTA': 'NPC_VENUE_BARISTA',
        'CAREER_ADULT_NPC_BARTENDER': 'NPC_VENUE_BARTENDER',
        'CAREER_ADULT_NPC_BARTENDER_COMPANY': 'NPC_VENUE_BARTENDER_COMPANY',
        'CAREER_ADULT_NPC_BONEHILDA': 'NPC_SERVICES_BONEHILDA',
        'CAREER_ADULT_NPC_BUTLER_SP09': 'NPC_SERVICES_BUTLER',
        'CAREER_ADULT_NPC_CAMERAOPERATOR': 'NPC_ACTOR_CAREER_CAMERA_OPERATOR',
        'CAREER_ADULT_NPC_CURIOSHOPOWNER': 'NPC_VENUE_CURIO_SHOP_OWNER',
        'CAREER_ADULT_NPC_DJ': 'NPC_VENUE_DJ',
        'CAREER_ADULT_NPC_ECOINSPECTOR': 'NPC_SPECIAL_ECO_INSPECTOR',
        'CAREER_ADULT_NPC_FATHERWINTER': 'NPC_SPECIAL_FATHER_WINTER',
        'CAREER_ADULT_NPC_FIREFIGHTER': 'NPC_SERVICES_FIREFIGHTER',
        'CAREER_ADULT_NPC_FISHERMAN': 'NPC_SPECIAL_MASTER_FISHER',
        'CAREER_ADULT_NPC_GARDENER': 'NPC_VENUE_COMMUNITY_GARDENER',
        'CAREER_ADULT_NPC_GARDENER_SERVICE': 'NPC_SERVICES_GARDENER',
        'CAREER_ADULT_NPC_GRIMREAPER': 'NPC_SPECIAL_GRIM_REAPER',
        'CAREER_ADULT_NPC_GYM_TRAINER': 'NPC_SPECIAL_GYM_TRAINER',
        'CAREER_ADULT_NPC_HAIRMAKEUPCHAIR_STYLIST': 'NPC_ACTOR_CAREER_HAIR_AND_MAKEUP_STYLIST',
        'CAREER_ADULT_NPC_HOMECHEF': 'NPC_SERVICES_HOME_CHEF',
        'CAREER_ADULT_NPC_LANDLORD': 'NPC_VENUE_LANDLORD',
        'CAREER_ADULT_NPC_LIBRARIAN': 'NPC_VENUE_LIBRARIAN',
        'CAREER_ADULT_NPC_MAID': 'NPC_SERVICES_MAID',
        'CAREER_ADULT_NPC_MAILMAN': 'NPC_SERVICES_MAIL',
        'CAREER_ADULT_NPC_MASSAGETHERAPIST': 'NPC_VENUE_MASSAGE_THERAPIST',
        'CAREER_ADULT_NPC_MASSAGETHERAPIST_SERVICE': 'NPC_SERVICES_MASSAGE_THERAPIST',
        'CAREER_ADULT_NPC_NANNY': 'NPC_SERVICES_NANNY',
        'CAREER_ADULT_NPC_OWNABLERESTAURANT_CHEF': 'NPC_BUSINESS_RESTAURANT_CHEF',
        'CAREER_ADULT_NPC_OWNABLERESTAURANT_HOST': 'NPC_BUSINESS_RESTAURANT_HOST',
        'CAREER_ADULT_NPC_OWNABLERESTAURANT_WAITER': 'NPC_BUSINESS_RESTAURANT_WAITER',
        'CAREER_ADULT_NPC_OWNABLEVETCLINIC_VET': 'NPC_BUSINESS_VET_CLINIC_VET',
        'CAREER_ADULT_NPC_PAPARAZZI': 'NPC_VENUE_PAPARAZZI',
        'CAREER_ADULT_NPC_PIZZADELIVERY': 'NPC_SERVICES_DELIVERIES_PIZZA',
        'CAREER_ADULT_NPC_POLLINATOR': 'NPC_STRANGER_VILLE_ALIEN_POLLINATOR',
        'CAREER_ADULT_NPC_PRODUCER': 'NPC_ACTOR_CAREER_PRODUCER',
        'CAREER_ADULT_NPC_PROFESSORNPC_ARTS': 'NPC_UNIVERSITY_PROFESSOR_ARTS',
        'CAREER_ADULT_NPC_PROFESSORNPC_SCIENCE': 'NPC_UNIVERSITY_PROFESSOR_SCIENCE',
        'CAREER_ADULT_NPC_RANGER': 'NPC_SPECIAL_RANGER',
        'CAREER_ADULT_NPC_REFLEXOLOGIST': 'NPC_VENUE_REFLEXOLOGIST',
        'CAREER_ADULT_NPC_REPAIR': 'NPC_SERVICES_REPAIR',
        'CAREER_ADULT_NPC_RESTAURANTCRITIC': 'NPC_BUSINESS_RESTAURANT_CRITIC',
        'CAREER_ADULT_NPC_RETAIL': 'NPC_BUSINESS_RETAIL_EMPLOYEE',
        'CAREER_ADULT_NPC_SPECIALEFFECTSOPERATOR': 'NPC_ACTOR_CAREER_SPECIAL_EFFECTS_OPERATOR',
        'CAREER_ADULT_NPC_STALLVENDOR': 'NPC_VENUE_STALL_VENDOR',
        'CAREER_ADULT_NPC_STRANGEVILLE_OGA': 'NPC_STRANGER_VILLE_OGA',
        'CAREER_ADULT_NPC_STRANGEVILLE_SCIENTIST': 'NPC_STRANGER_VILLE_SCIENTIST',
        'CAREER_ADULT_NPC_TRAGICCLOWN': 'NPC_SPECIAL_TRAGIC_CLOWN',
        'CAREER_ADULT_NPC_VENUE_BARREGULAR': 'NPC_VENUE_BAR_REGULAR',
        'CAREER_ADULT_NPC_WARDROBEPEDESTAL_STYLIST': 'NPC_ACTOR_CAREER_WARDROBE_STYLIST',
        'CAREER_ADULT_NPC_YOGAINSTRUCTOR_VENUE': 'NPC_SPECIAL_YOGA_INSTRUCTOR',
        'CAREER_ADULT_PAINTER': 'PAINTER',
        'CAREER_ADULT_PARTTIME_BABYSITTER': 'PART_TIME_BABY_SITTER_ADULT',
        'CAREER_ADULT_PARTTIME_BARISTA': 'PART_TIME_BARISTA_ADULT',
        'CAREER_ADULT_PARTTIME_DIVER': 'PART_TIME_DIVER',
        'CAREER_ADULT_PARTTIME_FASTFOOD': 'PART_TIME_FAST_FOOD_ADULT',
        'CAREER_ADULT_PARTTIME_FISHERMAN': 'PART_TIME_FISHERMAN',
        'CAREER_ADULT_PARTTIME_LIFEGUARD': 'PART_TIME_LIFEGUARD_ADULT',
        'CAREER_ADULT_PARTTIME_MANUALLABOR': 'PART_TIME_MANUAL_LABOR_ADULT',
        'CAREER_ADULT_PARTTIME_RETAIL': 'PART_TIME_RETAIL_ADULT',
        'CAREER_ADULT_SECRETAGENT': 'SECRET_AGENT',
        'CAREER_ADULT_STYLEINFLUENCER': 'STYLE_INFLUENCER',
        'CAREER_ADULT_TECHGURU': 'TECH_GURU',
        'CAREER_ADULT_WRITER': 'WRITER',
        'CAREER_BATUU': 'BATUU_MISSIONS',
        'CAREER_CHILD_GRADESCHOOL': 'SCHOOL_CHILD',
        'CAREER_DELIVERIES_FOODDELIVERYNPC': 'NPC_SERVICES_DELIVERIES_FOOD',
        'CAREER_ODDJOB': 'ODD_JOB',
        'CAREER_TEEN_BABYSITTER': 'PART_TIME_BABY_SITTER_TEEN',
        'CAREER_TEEN_BARISTA': 'PART_TIME_BARISTA_TEEN',
        'CAREER_TEEN_FASTFOOD': 'PART_TIME_FAST_FOOD_TEEN',
        'CAREER_TEEN_HIGHSCHOOL': 'SCHOOL_TEEN',
        'CAREER_TEEN_LIFEGUARD': 'PART_TIME_LIFEGUARD_TEEN',
        'CAREER_TEEN_MANUALLABOR': 'PART_TIME_MANUAL_LABOR_TEEN',
        'CAREER_TEEN_RETAIL': 'PART_TIME_RETAIL_TEEN',
        'CAREER_VOLUNTEER_DRAMACLUB': 'VOLUNTEER_DRAMA_CLUB',
        'CAREER_VOLUNTEER_E-SPORTS': 'VOLUNTEER_E_SPORTS',
        'CAREER_VOLUNTEER_SCOUTING': 'VOLUNTEER_SCOUTING',
        'DETECTIVECAREER_1': 'DETECTIVE',
        'UNIVERSITY_BASECAREER': 'UNIVERSITY',
        'UNIVERSITY_COURSESLOT_A': 'UNIVERSITY_COURSE_SLOT_A',
        'UNIVERSITY_COURSESLOT_B': 'UNIVERSITY_COURSE_SLOT_B',
        'UNIVERSITY_COURSESLOT_C': 'UNIVERSITY_COURSE_SLOT_C',
        'UNIVERSITY_COURSESLOT_D': 'UNIVERSITY_COURSE_SLOT_D',
    }


log = CommonLogRegistry().register_log(ModInfo.get_identity(), 's4cl_career_printer')
log.enable()


@Command('s4clib_dev.log_careers', command_type=CommandType.Live)
def _common_log_careers_ready_for_update(_connection: int=None) -> None:
    try:
        output = CheatOutput(_connection)
        output('Logging Careers')
        from sims4communitylib.utils.misc._s4cl_enum_value_update_utils import _S4CLEnumValueUpdateUtils
        from sims4communitylib.enums.common_career_ids import CommonCareerId
        not_found_values = _S4CLEnumValueUpdateUtils()._read_values_from_instances(Types.CAREER, _S4CLReaderForUpdate.CONVERSIONS, CommonCareerId, skip_not_found=True)
        output(f'Finished logging Careers. {len(not_found_values)} values were not found.')
    except Exception as ex:
        log.error('Error when logging careers.', exception=ex)
